### ISSUE TITLE
Suggestion: Add support for Iris.

### ISSUE THREAD

**Issue by KoxSosen** [XSoussou/ChopChop#2]
Hello!

Please add support for Iris. 
https://www.spigotmc.org/resources/iris-world-gen-the-dimension-engine.84586/updates
Iris has a lot of tree tpyes that does not work with chop chop. I can provide my test server as a workarea.

**Comment by XSoussou** [comment]
Hi,
This is gonna be a tough one haha !
Support for other plugins is definitely planned for future updates, so thank you very much for submitting this one !!
Though I really couldn't tell how long you'll have to wait for Iris support :(

Stay tuned :p

**Comment by KoxSosen** [comment]
Allright, I will! Thank you for the fast reply!

**Comment by KoxSosen** [comment]
Hi, is there any updates on the situation?

**Comment by XSoussou** [comment]
Hi,
I'm really sorry but you probably shouldn't expect this too soon :(
Right now I'm on a break from everything. I'm gonna start working on the plugin again soon though x)
You can expect this to come in a few weeks from now, don't worry I'm doing my best !

Thanks and Merry christmas :p

**Comment by KoxSosen** [comment]
Allright! Have a nice break, and happy holidays, Christmas and new year!

**Comment by KoxSosen** [comment]
I'm not using Iris anymore, but have a happy valentine day!
